build/admin.o: src/admin.c src/shuke.h src/defines.h src/version.h src/ae.h \
 src/anet.h src/zmalloc.h src/endianconv.h src/list.h src/log.h src/ds.h \
 src/sds.h src/dict.h src/rbtree.h src/str.h src/protocol.h \
 src/dpdk_module.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h src/utils.h
build/ae.o: src/ae.c src/ae.h src/zmalloc.h src/ae_epoll.c
build/anet.o: src/anet.c src/fmacros.h src/anet.h
build/dict.o: src/dict.c src/fmacros.h src/dict.h src/zmalloc.h
build/dpdk_module.o: src/dpdk_module.c src/dpdk_module.h src/shuke.h \
 src/defines.h src/version.h src/ae.h src/anet.h src/zmalloc.h \
 src/endianconv.h src/list.h src/log.h src/ds.h src/sds.h src/dict.h \
 src/rbtree.h src/str.h src/protocol.h 3rd/himongo/async.h \
 3rd/himongo/himongo.h 3rd/himongo/read.h 3rd/himongo/sds.h \
 3rd/himongo/proto.h 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h src/utils.h
build/dpdk_kni.o: src/dpdk_kni.c src/shuke.h src/defines.h src/version.h \
 src/ae.h src/anet.h src/zmalloc.h src/endianconv.h src/list.h src/log.h \
 src/ds.h src/sds.h src/dict.h src/rbtree.h src/str.h src/protocol.h \
 src/dpdk_module.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h
build/ds.o: src/ds.c src/endianconv.h src/zmalloc.h src/sds.h src/str.h \
 src/dict.h src/protocol.h src/log.h src/utils.h src/ds.h src/rbtree.h \
 src/defines.h
build/debug.o: src/debug.c src/shuke.h src/defines.h src/version.h src/ae.h \
 src/anet.h src/zmalloc.h src/endianconv.h src/list.h src/log.h src/ds.h \
 src/sds.h src/dict.h src/rbtree.h src/str.h src/protocol.h \
 src/dpdk_module.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h
build/mongo.o: src/mongo.c src/shuke.h src/defines.h src/version.h src/ae.h \
 src/anet.h src/zmalloc.h src/endianconv.h src/list.h src/log.h src/ds.h \
 src/sds.h src/dict.h src/rbtree.h src/str.h src/protocol.h \
 src/dpdk_module.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h src/utils.h
build/protocol.o: src/protocol.c src/fmacros.h src/endianconv.h src/zmalloc.h \
 src/protocol.h
build/rbtree.o: src/rbtree.c src/rbtree.h src/defines.h
build/rculfhash-mm-socket.o: src/rculfhash-mm-socket.c src/zmalloc.h
build/sds.o: src/sds.c src/sds.h src/zmalloc.h
build/shuke.o: src/shuke.c src/dpdk_module.h src/utils.h src/version.h src/ds.h \
 src/sds.h src/dict.h src/rbtree.h src/defines.h src/str.h src/protocol.h \
 src/zmalloc.h src/shuke.h src/ae.h src/anet.h src/endianconv.h \
 src/list.h src/log.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h src/asciilogo.h
build/str.o: src/str.c src/fmacros.h src/str.h
build/utils.o: src/utils.c src/fmacros.h src/log.h src/utils.h src/zmalloc.h
build/zone_parser.o: src/zone_parser.c src/fmacros.h src/str.h src/endianconv.h \
 src/protocol.h src/ds.h src/sds.h src/dict.h src/rbtree.h src/defines.h \
 src/log.h src/utils.h src/zmalloc.h
build/zmalloc.o: src/zmalloc.c src/zmalloc.h
build/tcpserver.o: src/tcpserver.c src/shuke.h src/defines.h src/version.h \
 src/ae.h src/anet.h src/zmalloc.h src/endianconv.h src/list.h src/log.h \
 src/ds.h src/sds.h src/dict.h src/rbtree.h src/str.h src/protocol.h \
 src/dpdk_module.h 3rd/himongo/async.h 3rd/himongo/himongo.h \
 3rd/himongo/read.h 3rd/himongo/sds.h 3rd/himongo/proto.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-compat.h \
 3rd/himongo/libbson/src/bson/bson-config.h \
 3rd/himongo/libbson/src/bson/bson-macros.h \
 3rd/himongo/libbson/src/bson/bson-stdint.h \
 3rd/himongo/libbson/src/bson/bson-atomic.h \
 3rd/himongo/libbson/src/bson/bson-context.h \
 3rd/himongo/libbson/src/bson/bson-types.h \
 3rd/himongo/libbson/src/bson/bson-endian.h \
 3rd/himongo/libbson/src/bson/bson-clock.h \
 3rd/himongo/libbson/src/bson/bson-decimal128.h \
 3rd/himongo/libbson/src/bson/bson-error.h \
 3rd/himongo/libbson/src/bson/bson-iter.h \
 3rd/himongo/libbson/src/bson/bson.h \
 3rd/himongo/libbson/src/bson/bson-json.h \
 3rd/himongo/libbson/src/bson/bson-keys.h \
 3rd/himongo/libbson/src/bson/bson-md5.h \
 3rd/himongo/libbson/src/bson/bson-memory.h \
 3rd/himongo/libbson/src/bson/bson-oid.h \
 3rd/himongo/libbson/src/bson/bson-reader.h \
 3rd/himongo/libbson/src/bson/bson-string.h \
 3rd/himongo/libbson/src/bson/bson-utf8.h \
 3rd/himongo/libbson/src/bson/bson-value.h \
 3rd/himongo/libbson/src/bson/bson-version.h \
 3rd/himongo/libbson/src/bson/bson-version-functions.h \
 3rd/himongo/libbson/src/bson/bson-writer.h \
 3rd/himongo/libbson/src/bson/bcon.h
